runtime: python311

entrypoint: gunicorn -k uvicorn.workers.UvicornWorker -b :$PORT main:app

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

env_variables:
  DATASET_BASE: "https://www.datos.gov.co/resource"
  DEFAULT_LIMIT: "100000"
  MAX_LIMIT: "1000000"
  DEFAULT_ANALYTIC_LIMIT: "100000"
  MIN_LIMIT_MUNICIPAL: "100000"
  MIN_LIMIT_DEPARTAMENTAL: "500000"
  PREVIEW_LIMIT: "10"
  ENVIRONMENT: "production"
